server:
  port: 8000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/books
    username: root
    password: password
#    url: jdbc:postgresql://localhost:5432/books
#    username: postgres
#    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver


